service: aws-node-rest-api-project

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  iamRoleStatements:
        - Effect: Allow
          Action: dynamodb:*
          Resource:
            - arn:aws:dynamodb:us-east-1:107248720807:table/usersTable

functions:
  verifyToken:
    handler: src/authVerifyToken.handler
    enviroment:
      JWT_SECRET: 1234PASSWORD
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /
          method: get
  registerUser:
    handler: src/registerUser.handler
    events:
      - http:
          path: /api/u/login
          method: post 
  getUsers:
    handler: src/getUsers.handler
    events:
      - http:
        path: /users
        method: get

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH


